// <copyright file="HandMeshController.cs" company="Google LLC">
//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>
// ----------------------------------------------------------------------

using System.Collections.Generic;
using AndroidXRUnitySamples.Variables;
using Google.XR.Extensions;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.XR;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;
using UnityEngine.XR.Hands.Samples.VisualizerSample;

namespace AndroidXRUnitySamples
{
    /// <summary>
    /// Manages hands when using Hand Mesh extension.
    /// </summary>
    public class HandMeshController : MonoBehaviour
    {
        /// <summary>
        /// The MeshId of the left hand mesh.
        /// It is a static variable so the value can be reused between scenes.
        /// </summary>
        private static MeshId _leftHandMeshId = MeshId.InvalidId;

        /// <summary>
        /// The MeshId of the right hand mesh.
        /// It is a static variable so the value can be reused between scenes.
        /// </summary>
        private static MeshId _rightHandMeshId = MeshId.InvalidId;

        /// <summary>
        /// The TrackableId of the left hand mesh.
        /// It is a static variable so the value can be reused between scenes.
        /// </summary>
        private static TrackableId _leftHandTrackableId = TrackableId.invalidId;

        /// <summary>
        /// The TrackableId of the right hand mesh.
        /// It is a static variable so the value can be reused between scenes.
        /// </summary>
        private static TrackableId _rightHandTrackableId = TrackableId.invalidId;

        /// <summary>
        /// The mesh filter of the left hand. The mesh data will be generated by XRMeshSubsystem.
        /// </summary>
        [SerializeField] private MeshFilter _leftHandMesh;

        /// <summary>
        /// The mesh filter of the right hand. The mesh data will be generated by XRMeshSubsystem.
        /// </summary>
        [SerializeField] private MeshFilter _rightHandMesh;

        /// <summary>
        /// The mesh filter of the left hand.
        /// </summary>
        [SerializeField] private MeshCollider _leftHandCollider;

        /// <summary>
        /// The mesh collider of the right hand.
        /// </summary>
        [SerializeField] private MeshCollider _rightHandCollider;

        /// <summary>
        /// Visualize hand mesh when the Use Hand Mesh setting is disabled.
        /// </summary>
        [SerializeField] private HandVisualizer _handVisualizer;

        /// <summary>
        /// The Use Hand Mesh setting.
        /// When true, use an ARMeshManager or an XRMeshSubsystem to visualize hand meshes.
        /// When false, use an HandVisualizer to visualize hand meshes.
        /// </summary>
        [SerializeField] private BoolVariable _useHandMesh;

        /// <summary>
        /// The XRMeshSubsystem which is accessed directly to generate hand meshes when there is no
        /// ARMeshManager enabled in the scene.
        /// </summary>
        private XRMeshSubsystem _meshSubsystem;

        /// <summary>
        /// The mesh renderer of the left hand mesh generated by an ARMeshManager.
        /// </summary>
        private MeshRenderer _arLeftHandMeshRenderer = null;

        /// <summary>
        /// The mesh renderer of the right hand mesh generated by an ARMeshManager.
        /// </summary>
        private MeshRenderer _arRightHandMeshRenderer = null;

        /// <summary>
        /// The original materials of the left hand mesh generated by an ARMeshManager.
        /// </summary>
        private Material[] _arLeftHandOriginalMaterials = null;

        /// <summary>
        /// The original materials of the right hand mesh generated by an ARMeshManager.
        /// </summary>
        private Material[] _arRightHandOriginalMaterials = null;

        /// <summary>
        /// Gets or sets a value indicating whether mesh colliders on hands are enabled.
        /// </summary>
        public bool EnableHandColliders
        {
            get => _leftHandCollider.enabled;

            set
            {
                _leftHandCollider.enabled = value;
                _rightHandCollider.enabled = value;
            }
        }

        /// <summary>
        /// Convert the game object name of an ARMeshManager-generated MeshFilter to a TrackableId.
        /// </summary>
        /// <param name="meshFilter">A MeshFilter generated by an ARMeshManager.</param>
        /// <returns>A TrackableId of the MeshFilter.</returns>
        public static TrackableId ConvertARMeshNameToTrackableId(MeshFilter meshFilter)
        {
            // Get the TrackableId from the game object name by excluding the "Mesh " prefix.
            const string namePrefix = "Mesh ";
            return new TrackableId(meshFilter.gameObject.name.Substring(namePrefix.Length));
        }

        /// <summary>
        /// Check if the first TrackableId is larger than the second TrackableId.
        /// </summary>
        /// <param name="lhs">The first TrackableId.</param>
        /// <param name="rhs">The second TrackableId.</param>
        /// <returns>Whether lhs is larger than rhs.</returns>
        private static bool IsLarger(TrackableId lhs, TrackableId rhs)
        {
            return (lhs.subId1, lhs.subId2).CompareTo((rhs.subId1, rhs.subId2)) > 0;
        }

        private void Start()
        {
            List<XRMeshSubsystem> meshSubsystems = new List<XRMeshSubsystem>();
            SubsystemManager.GetSubsystems(meshSubsystems);
            if (meshSubsystems.Count != 1)
            {
                Debug.LogError("Unexpected number of mesh subsystems."
                    + $"Expected 1, got {meshSubsystems.Count}.");
                _useHandMesh.Value = false;
                return;
            }

            _meshSubsystem = meshSubsystems[0];

            _useHandMesh.AddListener(HandleUseHandMeshChange);
            HandleUseHandMeshChange(_useHandMesh.Value);

            // Register the ARMeshManager meshes changed event in order to find the hand mesh ids
            // when ARMeshManager is enabled.
            var meshManager = Singleton.Instance.OriginManager.ARMeshManager;
            if (meshManager != null)
            {
                meshManager.meshesChanged += FindHandTrackableIdsFromARMeshManager;
            }
        }

        private void OnDestroy()
        {
            _useHandMesh.RemoveListener(HandleUseHandMeshChange);

            // Stop the XRMeshSubsystem if it is running.
            if (_meshSubsystem != null && _meshSubsystem.running)
            {
                _meshSubsystem.Stop();
            }

            // Unregister the ARMeshManager meshes changed event.
            var meshManager = Singleton.Instance.OriginManager.ARMeshManager;
            if (meshManager != null)
            {
                meshManager.meshesChanged -= FindHandTrackableIdsFromARMeshManager;
            }
        }

        private void Update()
        {
            if (!_useHandMesh.Value)
            {
                // When the Use Hand Mesh setting is disabled, it relies on the hand visualizer to
                // render hand meshes. Exit this Update().
                return;
            }

            // Use different methods to update hand meshes according to whether the ARMeshManager is
            // enabled or not.
            if (Singleton.Instance.OriginManager.EnableMeshManager)
            {
                UpdateHandMeshesByARMeshManager();
            }
            else
            {
                UpdateHandMeshesByXRMeshSubsystem();
            }
        }

        /// <summary>
        /// Handle an event where the Use Hand Mesh setting changes.
        /// There are totally three modes for hand meshes:
        /// 1. ARMeshManager Mode
        ///   - When the ARMeshManager is enabled, identify hand meshes generated by the
        ///     ARMeshManager and apply custom materials.
        /// 2. XRMeshSubsystem Mode
        ///   - When the ARMeshManager is disabled, directly access the XRMeshSubsystem to generate
        ///     hand meshes (without generating scene meshes).
        /// 3. HandVisualizer Mode
        ///   - Use the HandVisualizer to visualize skinned hand meshes using hand joint data.
        /// </summary>
        /// <param name="enable">The value of the Use Hand Mesh setting.</param>
        private void HandleUseHandMeshChange(bool enable)
        {
            _handVisualizer.drawMeshes = !enable;

            if (enable)
            {
                if (Singleton.Instance.OriginManager.EnableMeshManager)
                {
                    // In this mode, reuse the hand meshes generated by the ARMeshManager.
                    // Set up related mesh renderers and game objects.
                    SetHandMeshMaterialsForARMeshManagerMode(true);
                    EnableHandMeshGameObjectsForXRMeshSubsystemMode(false);
                }
                else
                {
                    // In this mode, access the XRMeshSubsystem directly to generate hand meshes.
                    // Set up related mesh renderers and game objects.
                    SetHandMeshMaterialsForARMeshManagerMode(false);
                    EnableHandMeshGameObjectsForXRMeshSubsystemMode(true);
                }
            }
            else
            {
                // In this mode, use the HandVisualizer to visualize hand meshes.
                // Set up related mesh renderers and game objects.
                SetHandMeshMaterialsForARMeshManagerMode(false);
                EnableHandMeshGameObjectsForXRMeshSubsystemMode(false);
            }
        }

        /// <summary>
        /// Set the hand mesh materials according to whether it is the ARMeshManager that is
        /// generating hand meshes or not.
        /// </summary>
        /// <param name="isInARMeshManagerMode">Whether it is the ARMeshManager that is
        /// generating hand meshes.</param>
        private void SetHandMeshMaterialsForARMeshManagerMode(bool isInARMeshManagerMode)
        {
            if (_arLeftHandMeshRenderer == null || _arRightHandMeshRenderer == null)
            {
                return;
            }

            if (isInARMeshManagerMode)
            {
                // Enable the hand mesh renderers.
                _arLeftHandMeshRenderer.enabled = true;
                _arRightHandMeshRenderer.enabled = true;

                // Use the materials of the member hand mesh filters.
                _arLeftHandMeshRenderer.materials =
                    _leftHandMesh.GetComponent<MeshRenderer>().materials;
                _arRightHandMeshRenderer.materials =
                    _rightHandMesh.GetComponent<MeshRenderer>().materials;

                // Copy the render group component.
                if (!_arLeftHandMeshRenderer.gameObject.TryGetComponent<SortingGroup>(out var _) &&
                     _leftHandMesh.gameObject.TryGetComponent<SortingGroup>(out var sortingGroup))
                {
                    var arHandSortingGroup =
                        _arLeftHandMeshRenderer.gameObject.AddComponent<SortingGroup>();
                    arHandSortingGroup.sortingLayerID = sortingGroup.sortingLayerID;
                    arHandSortingGroup.sortingOrder = sortingGroup.sortingOrder;
                    arHandSortingGroup.sortAtRoot = sortingGroup.sortAtRoot;
                }

                if (!_arRightHandMeshRenderer.gameObject.TryGetComponent<SortingGroup>(out var _) &&
                     _rightHandMesh.gameObject.TryGetComponent(out sortingGroup))
                {
                    var arHandSortingGroup =
                        _arRightHandMeshRenderer.gameObject.AddComponent<SortingGroup>();
                    arHandSortingGroup.sortingLayerID = sortingGroup.sortingLayerID;
                    arHandSortingGroup.sortingOrder = sortingGroup.sortingOrder;
                    arHandSortingGroup.sortAtRoot = sortingGroup.sortAtRoot;
                }
            }
            else
            {
                // Use the materials that the ARMeshManager uses when generating meshes.
                _arLeftHandMeshRenderer.materials = _arLeftHandOriginalMaterials;
                _arRightHandMeshRenderer.materials = _arRightHandOriginalMaterials;
            }
        }

        /// <summary>
        /// Enable the hand mesh game objects when the XRMeshSubsystem is used directly to generate
        /// hand meshes.
        /// </summary>
        /// <param name="isInXRMeshSubsystemMode">Whether the XRMeshSubsystem is used directly
        /// to generate hand meshes.</param>
        private void EnableHandMeshGameObjectsForXRMeshSubsystemMode(bool isInXRMeshSubsystemMode)
        {
            _leftHandMesh.gameObject.SetActive(isInXRMeshSubsystemMode);
            _rightHandMesh.gameObject.SetActive(isInXRMeshSubsystemMode);
        }

        /// <summary>
        /// Identify hand meshes generated by ARMeshManager, and save the corresponding ids.
        /// </summary>
        /// <param name="eventArgs">The event arguments of an ARMeshManager's meshes-changed event.
        /// </param>
        private void FindHandTrackableIdsFromARMeshManager(ARMeshesChangedEventArgs eventArgs)
        {
            if (_leftHandTrackableId != TrackableId.invalidId &&
                _rightHandTrackableId != TrackableId.invalidId)
            {
                // Hand mesh ids are already found. Unregister the meshes changed event.
                Singleton.Instance.OriginManager.ARMeshManager.meshesChanged
                    -= FindHandTrackableIdsFromARMeshManager;
                return;
            }

            // Need at least two updated meshes to get the ids of the two hands.
            if (eventArgs.updated.Count < 2)
            {
                return;
            }

            // Try to get the TrackableIds of hands from the updated meshes.
            if (!GetHandTrackableIds(eventArgs.updated, out _leftHandTrackableId,
                out _rightHandTrackableId))
            {
                Debug.LogWarning($"Failed to get hand TrackableIds. L: {_leftHandTrackableId}, " +
                    $"R: {_rightHandTrackableId}");
                return;
            }

            // Hand TrackableIds are found. Unregister the meshes changed event.
            Singleton.Instance.OriginManager.ARMeshManager.meshesChanged
                -= FindHandTrackableIdsFromARMeshManager;
        }

        /// <summary>
        /// Identify hand meshes generated by the ARMeshManager, and update the rendering of the
        /// hand meshes according to the member hand mesh filters.
        /// Assume the ARMeshManager is enabled.
        /// </summary>
        private void UpdateHandMeshesByARMeshManager()
        {
            if (_leftHandTrackableId == TrackableId.invalidId ||
                _rightHandTrackableId == TrackableId.invalidId)
            {
                // Not yet found the TrackableId of hand meshes.
                return;
            }

            // Find the mesh renderer of the hand meshes by the hand mesh TrackableIds.
            // The TrackableIds of hand meshes are already found (can be found in a scene where the
            // ARMeshManager is enabled or disabled).
            if (_arLeftHandMeshRenderer == null || _arRightHandMeshRenderer == null)
            {
                // Get the hand mesh filters.
                foreach (var meshFilter in Singleton.Instance.OriginManager.ARMeshManager.meshes)
                {
                    // Get the TrackableId of the mesh filter.
                    var trackableId = ConvertARMeshNameToTrackableId(meshFilter);

                    // Try to get the mesh renderer of the left hand or the right hand.
                    if (trackableId == _leftHandTrackableId)
                    {
                        _arLeftHandMeshRenderer = meshFilter.GetComponent<MeshRenderer>();
                    }
                    else if (trackableId == _rightHandTrackableId)
                    {
                        _arRightHandMeshRenderer = meshFilter.GetComponent<MeshRenderer>();
                    }

                    // Break the loop if both hands are found.
                    if (_arLeftHandMeshRenderer != null && _arRightHandMeshRenderer != null)
                    {
                        break;
                    }
                }

                // Back up the original materials that ARMeshManager generated.
                _arLeftHandOriginalMaterials = _arLeftHandMeshRenderer?.materials;
                _arRightHandOriginalMaterials = _arRightHandMeshRenderer?.materials;
            }

            // Use the materials of the member hand mesh filters (_leftHandMesh and _rightHandMesh)
            // for the hand mesh generated by the ARMeshManager.
            // Need to set every Update() in case that some other script is also modifying them.
            SetHandMeshMaterialsForARMeshManagerMode(true);
        }

        /// <summary>
        /// Update hand meshes using the XRMeshSubsystem, and save the hand mesh ids.
        /// </summary>
        private void UpdateHandMeshesByXRMeshSubsystem()
        {
            if (_meshSubsystem == null)
            {
                return;
            }

            // Start the XRMeshSubsystem in case it did not start.
            if (!_meshSubsystem.running)
            {
                _meshSubsystem.Start();
            }

            // Get mesh infos from the XRMeshSubsystem.
            List<MeshInfo> meshInfos = new List<MeshInfo>();
            if (!_meshSubsystem.TryGetMeshInfos(meshInfos))
            {
                Debug.LogError("XRMeshSubsystem.TryGetMeshInfos() failed.");
                return;
            }

            if (meshInfos.Count < 2)
            {
                Debug.LogError("Unexpected number of mesh infos from the mesh subsystem."
                    + $" Expected at least 2, got {meshInfos.Count}.");
                return;
            }

            // If the hand MeshIds are not found yet, find the hand MeshIds from the MeshInfos.
            if (_leftHandMeshId == MeshId.InvalidId || _rightHandMeshId == MeshId.InvalidId)
            {
                if (!GetHandMeshIds(meshInfos, out _leftHandMeshId, out _rightHandMeshId,
                    out _leftHandTrackableId, out _rightHandTrackableId))
                {
                    Debug.LogWarning($"Failed to get both hand mesh ids. L: {_leftHandMeshId}, " +
                        $"R: {_rightHandMeshId}");
                    return;
                }
            }

            // Get the MeshInfo indices of the two hands according to the hand MeshIds.
            if (!GetHandMeshInfoIndices(meshInfos, _leftHandMeshId, _rightHandMeshId,
                out int leftHandMeshInfoIndex, out int rightHandMeshInfoIndex))
            {
                Debug.LogWarning($"Failed to get the MeshInfo index of the two hands." +
                    $"L: {leftHandMeshInfoIndex}, R: {rightHandMeshInfoIndex}");
                return;
            }

            // Update the left hand mesh.
            if (meshInfos[leftHandMeshInfoIndex].ChangeState == MeshChangeState.Added ||
                meshInfos[leftHandMeshInfoIndex].ChangeState == MeshChangeState.Updated)
            {
                _meshSubsystem.GenerateMeshAsync(_leftHandMeshId, _leftHandMesh.mesh,
                    null, MeshVertexAttributes.Normals, OnHandMeshGenerated,
                    MeshGenerationOptions.ConsumeTransform);
                if (EnableHandColliders)
                {
                    _leftHandCollider.sharedMesh = _leftHandMesh.mesh;
                }
            }

            // Update the right hand mesh.
            if (meshInfos[rightHandMeshInfoIndex].ChangeState == MeshChangeState.Added ||
                meshInfos[rightHandMeshInfoIndex].ChangeState == MeshChangeState.Updated)
            {
                _meshSubsystem.GenerateMeshAsync(_rightHandMeshId, _rightHandMesh.mesh,
                    null, MeshVertexAttributes.Normals, OnHandMeshGenerated,
                    MeshGenerationOptions.ConsumeTransform);
                if (EnableHandColliders)
                {
                    _rightHandCollider.sharedMesh = _rightHandMesh.mesh;
                }
            }
        }

        /// <summary>
        /// It is a callback function used when generating hand meshes by the XRMeshSubsystem.
        /// The function sets the transform of the hand mesh game objects, which is required as
        /// the hand meshes are generated with the MeshGenerationOptions.ConsumeTransform flag.
        /// </summary>
        /// <param name="result">The mesh generation result.</param>
        private void OnHandMeshGenerated(MeshGenerationResult result)
        {
            if (result.Status != MeshGenerationStatus.Success)
            {
                Debug.LogError($"Mesh generation failed: {result.Status}");
                return;
            }

            if (_leftHandMeshId == MeshId.InvalidId || _rightHandMeshId == MeshId.InvalidId)
            {
                Debug.LogError($"{nameof(_leftHandMeshId)} or {nameof(_rightHandMeshId)} is not "
                    + "valid.");
                return;
            }

            // Get the mesh filter of the left hand or the right hand.
            MeshFilter meshFilter;
            if (result.MeshId == _leftHandMeshId)
            {
                meshFilter = _leftHandMesh;
            }
            else if (result.MeshId == _rightHandMeshId)
            {
                meshFilter = _rightHandMesh;
            }
            else
            {
                Debug.LogError($"Not a hand MeshId: {result.MeshId}");
                return;
            }

            // Set the transform of the hand mesh game object.
            meshFilter.transform.SetLocalPositionAndRotation(result.Position, result.Rotation);
            meshFilter.transform.localScale = result.Scale;
        }

        /// <summary>
        /// Get the MeshIds of the hand meshes from a list of MeshInfo.
        /// This method does not modify any member field.
        /// </summary>
        /// <param name="meshInfos">A list of MeshInfos.</param>
        /// <param name="leftHandMeshId">The output left hand MeshId.</param>
        /// <param name="rightHandMeshId">The output right hand MeshId.</param>
        /// <param name="leftHandTrackableId">The output left hand TrackableId.</param>
        /// <param name="rightHandTrackableId">The output right hand TrackableId.</param>
        /// <returns>Whether both the hand MeshIds are found in the input MeshInfos.</returns>
        private bool GetHandMeshIds(List<MeshInfo> meshInfos, out MeshId leftHandMeshId,
            out MeshId rightHandMeshId, out TrackableId leftHandTrackableId,
            out TrackableId rightHandTrackableId)
        {
            // Reset the input hand ids.
            leftHandMeshId = MeshId.InvalidId;
            rightHandMeshId = MeshId.InvalidId;
            leftHandTrackableId = TrackableId.invalidId;
            rightHandTrackableId = TrackableId.invalidId;

            // Try to get hand ids from the input MeshInfos.
            foreach (var meshInfo in meshInfos)
            {
                // If the MeshIds of the two hands are already found, break the loop.
                if (leftHandMeshId != MeshId.InvalidId && rightHandMeshId != MeshId.InvalidId)
                {
                    break;
                }

                // Skip if the MeshId is not from a hand mesh (it is from a scene mesh).
                if (_meshSubsystem.IsSceneMeshId(meshInfo.MeshId))
                {
                    continue;
                }

                if (leftHandMeshId == MeshId.InvalidId)
                {
                    // The left hand ids are not found yet. Assign the left hand ids.
                    leftHandMeshId = meshInfo.MeshId;
                    leftHandTrackableId = new TrackableId(leftHandMeshId.ToString());
                }
                else if (rightHandMeshId == MeshId.InvalidId)
                {
                    // The left hand ids are already found, but the right hand ids are not.
                    // Assign the right hand ids.
                    rightHandMeshId = meshInfo.MeshId;
                    rightHandTrackableId = new TrackableId(rightHandMeshId.ToString());
                }
            }

            // Check if the MeshIds the two hands are found.
            if (leftHandMeshId == MeshId.InvalidId || rightHandMeshId == MeshId.InvalidId)
            {
                return false;
            }

            // Make sure the left hand has the smaller ids among the two hands.
            if (IsLarger(leftHandTrackableId, rightHandTrackableId))
            {
                // The left hand id is larger. Swap the two hand ids.
                (leftHandMeshId, rightHandMeshId) =
                    (rightHandMeshId, leftHandMeshId);
                (leftHandTrackableId, rightHandTrackableId) =
                    (rightHandTrackableId, leftHandTrackableId);
            }

            return true;
        }

        /// <summary>
        /// Get the TrackableIds of hand meshes from a list of MeshFilters generated by
        /// an ARMeshManager.
        /// This method does not modify any member field.
        /// </summary>
        /// <param name="meshFilters">A list of MeshFilters generater by an ARMeshManager.</param>
        /// <param name="leftHandTrackableId">The output left hand TrackableId.</param>
        /// <param name="rightHandTrackableId">The output right hand TrackableId.</param>
        /// <returns>Whether both the hand TrackableIds are found in the input MeshFilters.
        /// </returns>
        private bool GetHandTrackableIds(List<MeshFilter> meshFilters,
            out TrackableId leftHandTrackableId, out TrackableId rightHandTrackableId)
        {
            // Reset the input hand ids.
            leftHandTrackableId = TrackableId.invalidId;
            rightHandTrackableId = TrackableId.invalidId;

            // Try to get hand ids from the input MeshFilters.
            foreach (var meshFilter in meshFilters)
            {
                // If the TrackableIds of the two hands are already found, break the loop.
                if (leftHandTrackableId != TrackableId.invalidId &&
                    rightHandTrackableId != TrackableId.invalidId)
                {
                    break;
                }

                var trackableId = ConvertARMeshNameToTrackableId(meshFilter);

                // Skip if the TrackableId is not from a hand mesh (it is from a scene mesh).
                if (_meshSubsystem.IsSceneMeshId(trackableId))
                {
                    continue;
                }

                if (leftHandTrackableId == TrackableId.invalidId)
                {
                    // The left hand TrackableId is not found yet. Assign the left hand id.
                    leftHandTrackableId = trackableId;
                }
                else if (rightHandTrackableId == TrackableId.invalidId)
                {
                    // The left hand TrackableId is already found, but the right hand id is not.
                    // Assign the right hand id.
                    rightHandTrackableId = trackableId;
                }
            }

            // Check if the TrackableIds the two hands are found.
            if (leftHandTrackableId == TrackableId.invalidId ||
                rightHandTrackableId == TrackableId.invalidId)
            {
                return false;
            }

            // Make sure the left hand has the smaller id among the two hands.
            if (IsLarger(leftHandTrackableId, rightHandTrackableId))
            {
                // The left hand id is larger. Swap the two ids.
                (leftHandTrackableId, rightHandTrackableId) =
                    (rightHandTrackableId, leftHandTrackableId);
            }

            return true;
        }

        /// <summary>
        /// Get the MeshInfos that belong to hand meshes from the input MeshInfos.
        /// This method does not modify any member field.
        /// </summary>
        /// <param name="meshInfos">A list of MeshInfos.</param>
        /// <param name="leftHandMeshId">The left hand MeshId.</param>
        /// <param name="rightHandMeshId">The right hand MeshId.</param>
        /// <param name="leftHandMeshInfoIndex">The output left hand MeshInfo index in the input
        /// meshInfos.</param>
        /// <param name="rightHandMeshInfoIndex">The output right hand MeshInfo index in the input
        /// meshInfos.</param>
        /// <returns>Whether the MeshInfo indices of the two hands are found.</returns>
        private bool GetHandMeshInfoIndices(List<MeshInfo> meshInfos, MeshId leftHandMeshId,
            MeshId rightHandMeshId, out int leftHandMeshInfoIndex, out int rightHandMeshInfoIndex)
        {
            // Reset the output indices.
            leftHandMeshInfoIndex = -1;
            rightHandMeshInfoIndex = -1;

            for (int i = 0; i < meshInfos.Count; ++i)
            {
                // Break the loop if both hands are found.
                if (leftHandMeshInfoIndex >= 0 && rightHandMeshInfoIndex >= 0)
                {
                    break;
                }

                // Check if it is the left hand or the right hand.
                if (meshInfos[i].MeshId == leftHandMeshId)
                {
                    leftHandMeshInfoIndex = i;
                }
                else if (meshInfos[i].MeshId == rightHandMeshId)
                {
                    rightHandMeshInfoIndex = i;
                }
            }

            // Return if both hand indices are found.
            return leftHandMeshInfoIndex >= 0 && rightHandMeshInfoIndex >= 0;
        }
    }
}
