// <copyright file="HandMeshController.cs" company="Google LLC">
//
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>
// ----------------------------------------------------------------------

using System.Collections.Generic;
using AndroidXRUnitySamples.Variables;
using Google.XR.Extensions;
using Unity.Collections;
using Unity.XR.CoreUtils.Collections;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.XR;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;
using UnityEngine.XR.Hands;
using UnityEngine.XR.Hands.Meshing;
using UnityEngine.XR.Hands.Samples.VisualizerSample;
using UnityEngine.XR.Management;

namespace AndroidXRUnitySamples
{
    /// <summary>
    /// Manages hands when using Hand Mesh extension.
    /// </summary>
    public class HandMeshController : MonoBehaviour
    {
        /// <summary>
        /// The mesh filter of the left hand. The mesh data will be generated by XRMeshSubsystem.
        /// </summary>
        [SerializeField] private MeshFilter _leftHandMesh;

        /// <summary>
        /// The mesh filter of the right hand. The mesh data will be generated by XRMeshSubsystem.
        /// </summary>
        [SerializeField] private MeshFilter _rightHandMesh;

        /// <summary>
        /// The mesh filter of the left hand.
        /// </summary>
        [SerializeField] private MeshCollider _leftHandCollider;

        /// <summary>
        /// The mesh collider of the right hand.
        /// </summary>
        [SerializeField] private MeshCollider _rightHandCollider;

        /// <summary>
        /// Visualize hand mesh when the Use Hand Mesh setting is disabled.
        /// </summary>
        [SerializeField] private HandVisualizer _handVisualizer;

        /// <summary>
        /// The Use Hand Mesh setting.
        /// When true, use an ARMeshManager or an XRMeshSubsystem to visualize hand meshes.
        /// When false, use an HandVisualizer to visualize hand meshes.
        /// </summary>
        [SerializeField] private BoolVariable _useHandMesh;

        private XRHandSubsystem _xrHandSubsystem;

        /// <summary>
        /// Gets or sets a value indicating whether mesh colliders on hands are enabled.
        /// </summary>
        public bool EnableHandColliders
        {
            get => _leftHandCollider.enabled;

            set
            {
                _leftHandCollider.enabled = value;
                _rightHandCollider.enabled = value;
            }
        }

        /// FIXME
        /// <summary>
        /// Convert the game object name of an ARMeshManager-generated MeshFilter to a TrackableId.
        /// </summary>
        /// <param name="meshFilter">A MeshFilter generated by an ARMeshManager.</param>
        /// <returns>A TrackableId of the MeshFilter.</returns>
        public static TrackableId ConvertARMeshNameToTrackableId(MeshFilter meshFilter)
        {
            // Get the TrackableId from the game object name by excluding the "Mesh " prefix.
            const string namePrefix = "Mesh ";
            return new TrackableId(meshFilter.gameObject.name.Substring(namePrefix.Length));
        }

        private void Start()
        {
            XRLoader loader = LoaderUtility.GetActiveLoader();
            _xrHandSubsystem = loader != null ? loader.GetLoadedSubsystem<XRHandSubsystem>() : null;

            if (_xrHandSubsystem == null)
            {
                Debug.LogError("XRHandSubsystem not found");
                return;
            }

            _xrHandSubsystem.updatedHands += HandleHandsUpdated;

            _useHandMesh.AddListener(HandleUseHandMeshChange);
            HandleUseHandMeshChange(_useHandMesh.Value);

            // Bug in the Unity package which will fail to init the Hand Mesh Data system on the
            // first run. Will be fixed in future releases of the package. For now hide hand meshes
            // until the data is successfully read.
            _leftHandMesh.gameObject.SetActive(false);
            _rightHandMesh.gameObject.SetActive(false);
        }

        private void OnDestroy()
        {
            if (_xrHandSubsystem != null)
            {
                _xrHandSubsystem.updatedHands -= HandleHandsUpdated;
            }

            _useHandMesh.RemoveListener(HandleUseHandMeshChange);
        }

        private void HandleHandsUpdated(
            XRHandSubsystem subsystem,
            XRHandSubsystem.UpdateSuccessFlags successFlags,
            XRHandSubsystem.UpdateType type)
        {
            if (!_useHandMesh.Value)
            {
                return;
            }

            var queryParams = new XRHandMeshDataQueryParams
            {
                allocator = Allocator.Temp
            };

            if (!subsystem.TryGetMeshData(out var meshData, ref queryParams))
            {
                return;
            }

            using (meshData)
            {
                var leftHandSuccessMask = XRHandSubsystem.UpdateSuccessFlags.LeftHandJoints |
                                           XRHandSubsystem.UpdateSuccessFlags.LeftHandRootPose;

                UpdateHandMesh(
                    successFlags, leftHandSuccessMask, _leftHandMesh, meshData.leftHand);

                var rightHandSuccessMask = XRHandSubsystem.UpdateSuccessFlags.RightHandJoints |
                                            XRHandSubsystem.UpdateSuccessFlags.RightHandRootPose;

                UpdateHandMesh(
                    successFlags, rightHandSuccessMask, _rightHandMesh, meshData.rightHand);
            }
        }

        void UpdateHandMesh(
            XRHandSubsystem.UpdateSuccessFlags successFlags,
            XRHandSubsystem.UpdateSuccessFlags mask,
            MeshFilter handMeshFilter,
            XRHandMeshData handMeshData)
        {
            if (handMeshFilter == null)
            {
                Debug.LogError("Expected valid handMeshFilter");
                return;
            }

            if ((successFlags & mask) != 0)
            {
                handMeshFilter.gameObject.SetActive(true);

                if (handMeshData.TryGetRootPose(out var rootPose))
                {
                    handMeshFilter.transform.localPosition = rootPose.position;
                    handMeshFilter.transform.localRotation = rootPose.rotation;
                }

                if (handMeshData.positions.Length == 0 || handMeshData.indices.Length == 0)
                {
                    Debug.LogWarning($"{handMeshFilter.name} MeshData contains invalid or empty " +
                                     $"positions or indices.");
                    return;
                }

                handMeshFilter.mesh.SetVertices(handMeshData.positions);
                handMeshFilter.mesh.SetIndices(handMeshData.indices, MeshTopology.Triangles, 0);
                handMeshFilter.mesh.SetNormals(handMeshData.normals);

                handMeshFilter.mesh.RecalculateBounds();
            }
            else
            {
                handMeshFilter.gameObject.SetActive(false);
            }
        }

        private void HandleUseHandMeshChange(bool enable)
        {
            _handVisualizer.drawMeshes = !enable;

            _leftHandMesh.gameObject.SetActive(enable);
            _rightHandMesh.gameObject.SetActive(enable);
        }
    }
}
